#
#  Yaml CI config for Gitlab See. http://docs.gitlab.com/ce/ci/yaml/README.html
#

image: git.oxfordnanolabs.local:4567/algorithm/sloika_docker:custard-16.04-latest


variables:
    RUN_ENVDIR: /taiyaki_venv/python3env
    RUN_ENV: ${RUN_ENVDIR}/bin/activate
    TEST_ENVDIR:  /taiyaki_venv/python3unittestenv
    TEST_ENV: ${TEST_ENVDIR}/bin/activate
    PYTEST_ARGS: -n2


stages:
    - build
    - test
    - release

format:
    stage: build
    script:
        - source $TEST_ENV && pip uninstall --yes flake8 && pip install 'autopep8>1.5'
        - source $TEST_ENV && find bin/ misc/ taiyaki/ test/ -name \*.py | xargs -P 1 autopep8 -j 2 --diff | tee pep8_differences.txt
        - if [ -s pep8_differences.txt ]; then false; fi
    artifacts:
        paths:
            - pep8_differences.txt
        expire_in: 1 week
        when: on_failure

flake8:
    stage: build
    script:
        - source $TEST_ENV && pip install flake8 &&
          find bin/ misc/ taiyaki/ test/ -name \*.py |
          flake8 -j 2 --show-source --statistics --tee --output-file=flake_results.txt
    artifacts:
        paths:
            - flake_results.txt
        expire_in: 1 week
        when: on_failure

unit_test:
    stage: test
    script:
        - make install envDir=${TEST_ENVDIR} && source $TEST_ENV && make unittest pyTestArgs=$PYTEST_ARGS envDir=${TEST_ENVDIR}


acceptance_test:
    stage: test
    script:
        - make install envDir=${TEST_ENVDIR} && source $TEST_ENV && make acctest pyTestArgs=$PYTEST_ARGS envDir=${TEST_ENVDIR}

workflow:
    stage: test
    script:
        - make install envDir=${RUN_ENVDIR} && source $RUN_ENV && make workflow envDir=${RUN_ENVDIR}
    only:
        - release
        - master
        - merge_request
        - /^ci_*/
